### ISSUE TITLE
This is not an issue!

### ISSUE THREAD

**Issue by bmsantos** [arrwhidev/nashorn-webpack-react-redux-boilerplate#1]
Thanks for this really cool sample project.

Based on this I was able to create an identical copy for Vert.x.

https://github.com/bmsantos/isomorphic-vertx-boilerplate/tree/master

**Comment by arrwhidev** [comment]
No problem :)

I've actually meant to experiment with Vert.x since hearing about it a few years ago but I've never got round to it.
