### ISSUE TITLE
server.min.js not found from ViewConfig

### ISSUE THREAD

**Issue by blured75** [arrwhidev/nashorn-webpack-react-redux-boilerplate#2]
Hi,

The file server.min.js is not found in the package. Should it be generated with webpack or other stuff ?

I've tryed npm install without specific result for this file generation.

I manage to compile and launch the server using mvn & java but I might miss something. Could you give me a hint about what do do ?

Best regards,
Blured.

**Comment by tobozo** [comment]
Use `npm build`

**Comment by blured75** [comment]
Does'nt work. Seems to base on dev stuff and not production. Does not fill  /dist directory. I've manage to do it by launching webpack : 
$ webpack --config ./webpack.production.config.js --progress --profile --colors

**Comment by serpentcross** [comment]
Guys, does someone have a solution?
App still doesn't work =(

This command not found: webpack --config ./webpack.production.config.js --progress --profile --colors

When I run this: npm build

Nothing happens.

Problem still exists! Please help! Thank you.

**Comment by arrwhidev** [comment]
Hi,

Apologies for slow response. I'll update the README with better instructions & I've also automated/improved the build process on a local branch which I will push up shortly.

Here's how to get up & running in the short term;
`cd src/main/webapp/react-app`
`npm install` - to install node modules.
`npm run build` - to build JS with webpack.
`mvn clean package` - to build webapp.

Hope that helps!

**Comment by arrwhidev** [comment]
@blured75 @serpentcross 

I've committed an update to the project which makes building easier and I've improved the README a lot too.
